<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>92b32eca-b506-4a56-9472-8479d500897c</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<!-- Identity -->
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />

		<!-- EF Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5" />

		<!-- Config -->

		<!-- JWT -->
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />

		<!-- DB -->
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
	</ItemGroup>

</Project>